services:
  arpellastores:
    image: evansmungai/arpellastores:latest
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # HTTPS
    env_file:
      .env
    volumes:
      - /root/cloudflare.pfx:/https/cloudflare.pfx:ro
    environment:
        ASPNETCORE_ENVIRONMENT: "Production"
        HTTPS_PFX_PATH: "/https/cloudflare.pfx"
        HTTPS_PFX_PASSWORD: "${CERT_PASSWORD}"
    restart: always
