services:
  arpellastores:
    image: evansmungai/arpellastores:latest
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # HTTPS
    env_file:
      .env
    volumes:
      - /etc/ssl/myapp:/certs:ro
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      HTTPS_PFX_PATH: /certs/bundle.pfx
      HTTPS_PFX_PASSWORD: arpellastores
    restart: always
