services:
  arpellastores:
    image: evansmungai/arpellastores:latest
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # HTTPS
    env_file:
      .env
    volumes:
      - /arpella-stores/certificates/cloudflare.pfx:/https/cloudflare.pfx:ro
      - /arpella-stores/certificates/ca.pem:/certs/ca.pem:ro
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - HTTPS_PFX_PATH=/etc/ssl/private/arpella1.pfx
        - HTTPS_PFX_PASSWORD=${CERT_PASSWORD}
    restart: always
