name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./ArpellaStores
        file: ./ArpellaStores/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/arpellastores:latest

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" | base64 -d > .env

    - name: Generate .pfx from Cloudflare certs
      run: |
        mkdir certs
        echo "${{ secrets.CLOUDFLARE_CERT_PEM }}" > certs/cert.pem
        echo "${{ secrets.CLOUDFLARE_KEY_PEM }}" > certs/key.pem
        openssl pkcs12 -export \
          -in certs/cert.pem \
          -inkey certs/key.pem \
          -out certs/cloudflare.pfx \
          -passout pass:${{ secrets.CERT_PASSWORD }}

    - name: Copy files to VPS
      run: |
        echo "${{ secrets.VPS_SSH_KEY }}" > id_rsa
        chmod 600 id_rsa

        scp -i id_rsa -o StrictHostKeyChecking=no \
        docker-compose.yml docker-compose.override.yml .env certs/cloudflare.pfx \
        ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/

    - name: SSH into VPS and deploy containers
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root
          docker-compose pull
          docker-compose down
          docker-compose up -d