name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./ArpellaStores
        file: ./ArpellaStores/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/arpellastores:latest

    - name: Prepare deployment files
      run: |
        echo "${{ secrets.ENV_FILE }}" | base64 -d > .env
        mkdir certs
        echo "${{ secrets.CLOUDFLARE_CERT_PEM }}" | base64 -d > certs/cert.pem
        echo "${{ secrets.CLOUDFLARE_KEY_PEM }}" | base64 -d > certs/key.pem
        echo "${{ secrets.AIVEN_CA_PEM }}" | base64 -d > certs/ca.pem

        openssl pkcs12 -export \
          -in certs/cert.pem \
          -inkey certs/key.pem \
          -out certs/cloudflare.pfx \
          -passout pass:${{ secrets.CERT_PASSWORD }}

    - name: Copy files to VPS
      run: |
        echo "${{ secrets.VPS_SSH_KEY }}" > id_rsa
        chmod 600 id_rsa

        scp -i id_rsa -o StrictHostKeyChecking=no \
          docker-compose.yml .env certs/cloudflare.pfx certs/ca.pem \
          ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/

    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root
          docker-compose pull
          docker-compose down
          docker-compose up -d